<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <AssemblyName>AsyncLua</AssemblyName>
    <RootNamespace>AsyncLua</RootNamespace>
    <Description>An extended Lua interpreter for C#, optimized for concurrency with async/await patterns.</Description>
    <Authors>RomeCore</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>lua;interpreter;async;await;concurrency;scripting;vm;bytecode</PackageTags>
    <RepositoryUrl>https://github.com/RomeCore/AsyncLua</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="RCParsing" Version="5.3.0" />
  </ItemGroup>

</Project>
